### ISSUE TITLE
No existe el todo_8

### ISSUE THREAD

**Issue by juancol88** [proyectos-mejorandola/pokedex#4]
Buenos días,

Haciendo el comando git checkout todo_8, github devuelve un mensaje indicando que este no existe, hago el comando git tag y solo lista hasta el todo_8, agradecería la correción de esto para terminar el curso correctamente.

**Comment by julianduque** [comment]
el `todo_8` nunca se implementó la solución, quedaba como tarea (o donde estas viendo el `todo_8`) ?

**Comment by juancol88** [comment]
Muchas gracias por la aclaración.
